feat: Added profile lookup using a Udemy profile URL
flytegg/ls-discord-bot pull request #213
Opened 2023-11-02 17:00 UTC by eendjebernard

## Change log
- Add profile lookup using Udemy profile URL

## Checklist
- [ ] I've tested this feature thoroughly.

2023-11-02 19:39 UTC, akkkih commented
Hey @eendjebernard, the code looks good so far but I'm pretty sure you can reduce and simplify the amount of if statements in the ProfileCommand.kt file :)

2023-11-02 19:49 UTC, eendjebernard commented
> Hey @eendjebernard, the code looks good so far but I'm pretty sure you can reduce and simplify the amount of if statements in the ProfileCommand.kt file :)

I will look at it tomorrow but I already did my best reducing it. It was even worse before.

2023-11-03 08:51 UTC, joshbker requested changes
Please make requested amendments to the when expression, thanks <3

2023-11-03 08:51 UTC, joshbker commented on src/main/kotlin/com/learnspigot/bot/profile/ProfileCommand.kt
> +        val embed: MessageEmbed = when {
I like the change to a when statement, but this can be improved even further with more concise conditions, I'll leave separate examples further on

2023-11-03 08:51 UTC, joshbker commented on src/main/kotlin/com/learnspigot/bot/profile/ProfileCommand.kt
> +            user == null && url == null -> {
This is a 1 liner, no need to open a body

2023-11-03 08:51 UTC, joshbker commented on src/main/kotlin/com/learnspigot/bot/profile/ProfileCommand.kt
> +                embed()
We are constantly repeating the process of creating the same embed, we can move this logic out into a function, something like "createProfileLookupEmbed", e.g.
```kt
fun createProfileLookupEmbed(title: String, description: String): MessageEmbed = embed()
    .setTitle("Profile Lookup")
    .addField(title, description, false)
    .build()
```
We can then use this everywhere we need it, and we can specify a title and description to make our when less "heavy". F.x.
```kt
user != null && url != null -> createProfileLookupEmbed("Please choose", "Please make a choice whether you want to use a user or use a URL.")
```

2023-11-03 08:51 UTC, joshbker commented on src/main/kotlin/com/learnspigot/bot/profile/ProfileCommand.kt
> +                embed()
By taking this out into a function, we can actually make all of these conditions 1 liners

2023-11-03 09:29 UTC, joshbker approved these changes

2023-11-03 09:30 UTC, merged