Added force-close command and made manual closing impossible for help-threads
flytegg/ls-discord-bot pull request #90
Opened 2022-12-28 23:34 UTC by Zcamt

Closes #80 

As a result, a new force-close command has been added to allow for the closing of a ticket if needed.

2022-12-29 10:06 UTC, Nuckerr requested changes
Are we saving the dontReopen list?

2022-12-29 10:06 UTC, Nuckerr commented on src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt
> +            if(it.newValue != true) return@listener
!it.newValue

2022-12-29 14:53 UTC, Zcamt commented
> Are we saving the dontReopen list?

I don't think we need to.
A channel is only added when the close button is clicked or when force-close I ran. So unless the bot breaks down mid-event, I don't think we need to save it other than just in memory. 

However maybe we should remove the channel from the list afterward, or will that be done by GC?

2022-12-29 15:31 UTC, Nuckerr commented
Probably needs removing

2023-01-03 14:48 UTC, Nuckerr approved these changes
Just need to test locally

2023-01-18 22:41 UTC, Zcamt commented
> Just need to test locally

Mr Nucker, were you able to test it? :)

2023-01-19 07:40 UTC, Nuckerr commented
I have been extremely busy + forgot about this. Shall to tonight

2023-02-01 20:38 UTC, Zcamt commented
> I have been extremely busy + forgot about this. Shall to tonight

May I just merge this myself? Or would you still like to test it before?

2023-02-02 17:52 UTC, Nuckerr commented
I get this error:
```
17:51:33.818 ForkJoinPool.commonPool-worker-1              RestAction      ERROR  RestAction queue returned failure: [ErrorResponseException] 50083: Thread is archived
net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200)
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invokeSuspend(ThreadCloseCommand.kt:53)
	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invoke(ThreadCloseCommand.kt)
	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invoke(ThreadCloseCommand.kt)
	at dev.minn.jda.ktx.events.EventsKt$onCommand-5_5nbZA$$inlined$listener-Kx4hsE0$1.onEvent(CoroutineEventManager.kt:153)
	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener$suspendImpl(CoroutineEventManager.kt:101)
	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener(CoroutineEventManager.kt)
	at dev.minn.jda.ktx.events.CoroutineEventManager$handle$1.invokeSuspend(CoroutineEventManager.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
and this happens in discord :/
![image](https://user-images.githubusercontent.com/62883418/216403136-e6626b48-22ad-4f4b-845f-db2d00080edc.png)

2023-02-02 21:47 UTC, Zcamt commented
> I get this error:
> 
> ```
> 17:51:33.818 ForkJoinPool.commonPool-worker-1              RestAction      ERROR  RestAction queue returned failure: [ErrorResponseException] 50083: Thread is archived
> net.dv8tion.jda.api.exceptions.ContextException: null
> 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
> 	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200)
> 	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74)
> 	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
> 	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
> 	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invokeSuspend(ThreadCloseCommand.kt:53)
> 	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invoke(ThreadCloseCommand.kt)
> 	at com.learnspigot.bot.command.ThreadCloseCommand$forceThreadCloseCommand$1$1.invoke(ThreadCloseCommand.kt)
> 	at dev.minn.jda.ktx.events.EventsKt$onCommand-5_5nbZA$$inlined$listener-Kx4hsE0$1.onEvent(CoroutineEventManager.kt:153)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener$suspendImpl(CoroutineEventManager.kt:101)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager.runListener(CoroutineEventManager.kt)
> 	at dev.minn.jda.ktx.events.CoroutineEventManager$handle$1.invokeSuspend(CoroutineEventManager.kt:91)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> ```
> 
> and this happens in discord :/ ![image](https://user-images.githubusercontent.com/62883418/216403136-e6626b48-22ad-4f4b-845f-db2d00080edc.png)

Could you expand on when this happens? I've tested this countless times and I haven't had this happen at all, are you trying to do this in a thread that's already closed?

2023-02-02 22:55 UTC, Zcamt commented
I've now tested the build I've pushed - everything works as expected and I can't reproduce any error. Please let me know if you end up getting any

2023-02-07 13:22 UTC, Nuckerr commented
I will retest this. Also, mind resolving merge conflicts ❤️

2023-02-07 18:27 UTC, Zcamt commented
> I will retest this. Also, mind resolving merge conflicts ❤️

Awesome and sure thing, will fix those rn

2023-03-16 18:57 UTC, merged

2023-03-16 18:57 UTC, sttephen commented
Great feature. Just going to merge this. 

![disaster-girl](https://user-images.githubusercontent.com/35041891/225725144-7018879e-d386-4d92-8753-1d0060965448.jpg)